version: "3"
services:
  mongodb:
    image: mongo:3.2
    ports:
      - "27017"
    volumes:
      - "/data/db"

  label-coach:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
